-- Seed global report templates from current product defaults.

INSERT INTO report_templates (
  workspace_id,
  slug,
  title,
  type_id,
  category,
  description,
  cadence,
  coverage,
  confidence,
  owner,
  tags,
  config,
  is_active,
  version
)
VALUES
  (
    NULL,
    'temp-overview-board',
    'Executive Summary',
    'overview',
    'summary',
    'Top-line comp health, market movement, and budget signals.',
    'Monthly',
    'All roles · GCC',
    'High',
    'People Analytics',
    ARRAY['Board Check', 'Trends', 'Budget'],
    '{"blocks":["market_trend","budget_guardrail","exec_headline"]}'::jsonb,
    true,
    1
  ),
  (
    NULL,
    'temp-overview-ops',
    'Ops Scoreboard',
    'overview',
    'summary',
    'Operational KPIs for compensation cycles and approvals.',
    'Weekly',
    'All regions · 18 markets',
    'High',
    'Comp Ops',
    ARRAY['Board Check', 'Trends', 'Budget'],
    '{"blocks":["cycle_velocity","approval_sla","throughput"]}'::jsonb,
    true,
    1
  ),
  (
    NULL,
    'temp-benchmark-role',
    'Role Benchmark Pack',
    'benchmark',
    'benchmark',
    'Role family benchmarks with percentile movement.',
    'On Demand',
    'Engineering · GCC',
    'High',
    'Total Rewards',
    ARRAY['Board Check', 'Trends', 'Budget'],
    '{"blocks":["percentile_distribution","role_spread","market_delta"]}'::jsonb,
    true,
    1
  ),
  (
    NULL,
    'temp-benchmark-geo',
    'Geo Compensation',
    'benchmark',
    'benchmark',
    'Location-based benchmarking for hiring hubs.',
    'Quarterly',
    'UAE · KSA · Qatar',
    'Medium',
    'Talent Partners',
    ARRAY['Location', 'Hot markets'],
    '{"blocks":["geo_heatmap","market_gap","hiring_pressure"]}'::jsonb,
    true,
    1
  ),
  (
    NULL,
    'temp-compliance-equity',
    'Pay Equity Review',
    'compliance',
    'compliance',
    'Identify pay equity gaps and remediation actions.',
    'Monthly',
    'All business units',
    'High',
    'Compliance',
    ARRAY['Equity', 'Audit'],
    '{"blocks":["equity_gap","variance_band","remediation_plan"]}'::jsonb,
    true,
    1
  ),
  (
    NULL,
    'temp-compliance-policy',
    'Policy Adherence',
    'compliance',
    'compliance',
    'Tracks out-of-band offers and approval exceptions.',
    'On Demand',
    'All offers',
    'Medium',
    'People Ops',
    ARRAY['Exceptions', 'Approvals'],
    '{"blocks":["exception_log","approval_matrix","policy_risk"]}'::jsonb,
    true,
    1
  ),
  (
    NULL,
    'temp-custom-workforce',
    'Workforce Plan Builder',
    'custom',
    'custom',
    'Tailor scenarios for headcount, comp, and budget.',
    'On Demand',
    'Custom selection',
    'Medium',
    'Strategic HR',
    ARRAY['Scenario', 'Headcount'],
    '{"blocks":["scenario_inputs","cost_projection","headcount_mix"]}'::jsonb,
    true,
    1
  ),
  (
    NULL,
    'temp-custom-offer',
    'Offer Audit Pack',
    'custom',
    'custom',
    'Build a pack for leadership sign-off on offers.',
    'On Demand',
    'Selected roles',
    'High',
    'Recruiting Ops',
    ARRAY['Approvals', 'Offer notes'],
    '{"blocks":["offer_summary","exception_reason","signoff_queue"]}'::jsonb,
    true,
    1
  )
ON CONFLICT (slug, version) WHERE workspace_id IS NULL DO NOTHING;
