-- Seed 20 additional live ingestion sources (public/no-auth APIs).
INSERT INTO ingestion_sources (
  slug,
  name,
  description,
  category,
  regions,
  license_url,
  terms_summary,
  approved_for_commercial,
  needs_review,
  update_cadence,
  expected_fields,
  enabled,
  config,
  updated_at
)
VALUES
  (
    'uae_fcsc_workforce_comp',
    'UAE FCSC Workforce Compensation',
    'Dubai Pulse workforce compensation open API.',
    'govt',
    ARRAY['GCC', 'AE'],
    'https://opendata.fcsc.gov.ae/',
    'Open data portal source; verify latest reuse terms per dataset.',
    true,
    false,
    'daily',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://www.dubaipulse.gov.ae/api/explore/v2.1/catalog/datasets/dsc_workforce_compensation-open-api/records"}'::jsonb,
    now()
  ),
  (
    'uae_fcsc_public_admin_paid',
    'UAE FCSC Paid Employees (Public Admin)',
    'UAE paid employees in public administration and defense.',
    'govt',
    ARRAY['GCC', 'AE'],
    'https://opendata.fcsc.gov.ae/',
    'Open data portal source; verify latest reuse terms per dataset.',
    true,
    false,
    'weekly',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://opendata.fcsc.gov.ae/api/explore/v2.1/catalog/datasets/paid-employees-public-administration-defense-and-compulsory-social-security-industry/records"}'::jsonb,
    now()
  ),
  (
    'uae_fcsc_gov_compensation',
    'UAE FCSC Government Compensation',
    'General government compensation of employees dataset.',
    'govt',
    ARRAY['GCC', 'AE'],
    'https://opendata.fcsc.gov.ae/',
    'Open data portal source; verify latest reuse terms per dataset.',
    true,
    false,
    'weekly',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://opendata.fcsc.gov.ae/api/explore/v2.1/catalog/datasets/general-government-compensation-of-employees/records"}'::jsonb,
    now()
  ),
  (
    'oman_ncsi_wages',
    'Oman NCSI Wages and Salaries',
    'NCSI wages and salaries open dataset.',
    'govt',
    ARRAY['GCC', 'OM'],
    'https://data.ncsi.gov.om/',
    'National open data source; verify dataset-level terms.',
    true,
    false,
    'weekly',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://data.ncsi.gov.om/api/explore/v2.1/catalog/datasets/wages-and-salaries/records"}'::jsonb,
    now()
  ),
  (
    'oman_labour_private',
    'Oman Labour Market (Private)',
    'Private-sector labor market series from Oman data portal.',
    'govt',
    ARRAY['GCC', 'OM'],
    'https://data.gov.om/',
    'Open data source; verify dataset-level reuse rights.',
    true,
    false,
    'weekly',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://data.gov.om/api/explore/v2.1/catalog/datasets/labour-market-private-sector/records"}'::jsonb,
    now()
  ),
  (
    'oman_labour_public',
    'Oman Labour Market (Public)',
    'Public-sector labor market series from Oman data portal.',
    'govt',
    ARRAY['GCC', 'OM'],
    'https://data.gov.om/',
    'Open data source; verify dataset-level reuse rights.',
    true,
    false,
    'weekly',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://data.gov.om/api/explore/v2.1/catalog/datasets/labour-market-public-sector/records"}'::jsonb,
    now()
  ),
  (
    'qatar_labor_force_sector',
    'Qatar Labor Force by Sector',
    'Qatar labor force by sector dataset.',
    'govt',
    ARRAY['GCC', 'QA'],
    'https://www.data.gov.qa/',
    'Qatar open data portal; verify dataset-level terms.',
    true,
    false,
    'daily',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://www.data.gov.qa/api/explore/v2.1/catalog/datasets/number-of-labor-force-by-sector-thousand/records"}'::jsonb,
    now()
  ),
  (
    'qatar_inactive_population',
    'Qatar Economically Inactive Population',
    'Quarterly labor force inactive population statistics.',
    'govt',
    ARRAY['GCC', 'QA'],
    'https://www.data.gov.qa/',
    'Qatar open data portal; verify dataset-level terms.',
    true,
    false,
    'daily',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://www.data.gov.qa/api/explore/v2.1/catalog/datasets/labor-force-statistics-number-of-economically-inactive-population-aged-15-years-and-above-by-quarter/records"}'::jsonb,
    now()
  ),
  (
    'bahrain_lmra_work_permits',
    'Bahrain LMRA Work Permits',
    'LMRA active work permits dataset from Bahrain Open Data.',
    'govt',
    ARRAY['GCC', 'BH'],
    'https://www.data.gov.bh/',
    'Bahrain open data source; verify dataset-level terms.',
    true,
    false,
    'daily',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://www.data.gov.bh/api/explore/v2.1/catalog/datasets/lmra1-active-work-permits-for-expatriate/records"}'::jsonb,
    now()
  ),
  (
    'bahrain_labor_market',
    'Bahrain Labor Market Statistics',
    'Labor market statistics dataset from Bahrain portals.',
    'govt',
    ARRAY['GCC', 'BH'],
    'https://www.data.gov.bh/',
    'Bahrain open data source; verify dataset-level terms.',
    true,
    false,
    'weekly',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://www.data.gov.bh/api/explore/v2.1/catalog/datasets/labour-market-regulatory-authority-statistics/records"}'::jsonb,
    now()
  ),
  (
    'kuwait_open_labor',
    'Kuwait Open Labor Data',
    'Kuwait labor-force related open dataset endpoint.',
    'govt',
    ARRAY['GCC', 'KW'],
    'https://e.gov.kw/',
    'Kuwait open data source; verify dataset-level terms.',
    true,
    false,
    'weekly',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://e.gov.kw/api/explore/v2.1/catalog/datasets/labor-force-open-data/records"}'::jsonb,
    now()
  ),
  (
    'saudi_gastat_labor',
    'Saudi GASTAT Labor Indicators',
    'Labor market indicators from Saudi economic data platform.',
    'govt',
    ARRAY['GCC', 'SA'],
    'https://economics.stats.gov.sa/',
    'Saudi government source; verify dataset-level terms.',
    true,
    false,
    'daily',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://economics.stats.gov.sa/api/explore/v2.1/catalog/datasets/labor-market-indicators/records"}'::jsonb,
    now()
  ),
  (
    'jordan_dos_labor',
    'Jordan DOS Labor Statistics',
    'Jordan labor market open dataset endpoint.',
    'govt',
    ARRAY['MENA'],
    'https://opendata.dos.gov.jo/',
    'Jordan open data source; verify dataset-level terms.',
    true,
    false,
    'weekly',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","endpoint":"https://opendata.dos.gov.jo/api/explore/v2.1/catalog/datasets/labour-market-statistics/records"}'::jsonb,
    now()
  ),
  (
    'wb_gcc_unemployment',
    'World Bank GCC Unemployment',
    'World Bank API unemployment indicator for GCC countries.',
    'market',
    ARRAY['GCC', 'Global'],
    'https://api.worldbank.org/',
    'World Bank open data API.',
    true,
    false,
    'daily',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","indicator":"SL.UEM.TOTL.ZS"}'::jsonb,
    now()
  ),
  (
    'wb_gcc_wage_workers',
    'World Bank GCC Wage Workers',
    'World Bank wage and salaried workers indicator for GCC countries.',
    'market',
    ARRAY['GCC', 'Global'],
    'https://api.worldbank.org/',
    'World Bank open data API.',
    true,
    false,
    'daily',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","indicator":"SL.EMP.WORK.ZS"}'::jsonb,
    now()
  ),
  (
    'wb_gcc_gdp_per_capita',
    'World Bank GCC GDP per Capita',
    'World Bank GDP per capita indicator for GCC countries.',
    'market',
    ARRAY['GCC', 'Global'],
    'https://api.worldbank.org/',
    'World Bank open data API.',
    true,
    false,
    'daily',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","indicator":"NY.GDP.PCAP.CD"}'::jsonb,
    now()
  ),
  (
    'wb_mena_gdp_per_capita',
    'World Bank MENA GDP per Capita',
    'World Bank GDP per capita indicator for MENA aggregate.',
    'market',
    ARRAY['MENA', 'Global'],
    'https://api.worldbank.org/',
    'World Bank open data API.',
    true,
    false,
    'daily',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","indicator":"NY.GDP.PCAP.CD"}'::jsonb,
    now()
  ),
  (
    'wb_gcc_labor_participation',
    'World Bank GCC Labor Participation',
    'World Bank labor-force participation indicator for GCC countries.',
    'market',
    ARRAY['GCC', 'Global'],
    'https://api.worldbank.org/',
    'World Bank open data API.',
    true,
    false,
    'daily',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","indicator":"SL.TLF.CACT.ZS"}'::jsonb,
    now()
  ),
  (
    'wb_gcc_employed_services',
    'World Bank GCC Employed in Services',
    'World Bank employed in services indicator for GCC countries.',
    'market',
    ARRAY['GCC', 'Global'],
    'https://api.worldbank.org/',
    'World Bank open data API.',
    true,
    false,
    'daily',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","indicator":"SL.SRV.EMPL.ZS"}'::jsonb,
    now()
  ),
  (
    'wb_gcc_employed_industry',
    'World Bank GCC Employed in Industry',
    'World Bank employed in industry indicator for GCC countries.',
    'market',
    ARRAY['GCC', 'Global'],
    'https://api.worldbank.org/',
    'World Bank open data API.',
    true,
    false,
    'daily',
    '["role","level","location","currency","p10","p25","p50","p75","p90","sample_size"]'::jsonb,
    true,
    '{"health":"live","indicator":"SL.IND.EMPL.ZS"}'::jsonb,
    now()
  )
ON CONFLICT (slug) DO UPDATE
SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  regions = EXCLUDED.regions,
  license_url = EXCLUDED.license_url,
  terms_summary = EXCLUDED.terms_summary,
  approved_for_commercial = EXCLUDED.approved_for_commercial,
  needs_review = EXCLUDED.needs_review,
  update_cadence = EXCLUDED.update_cadence,
  expected_fields = EXCLUDED.expected_fields,
  enabled = EXCLUDED.enabled,
  config = EXCLUDED.config,
  updated_at = now();
